# Generated by Django 4.1 on 2023-05-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homerental", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_homeowner",
            field=models.BooleanField(default=False),
        ),
    ]
