# Generated by Django 4.1 on 2023-05-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homerental", "0003_profile_location_profile_phone"),
    ]

    operations = [
        migrations.RenameModel(old_name="Home", new_name="HomeAdd",),
    ]
